2023.03.31 13:22:52 LOG5[ui]: stunnel 5.69 on aarch64-apple-darwin22.3.0 platform
2023.03.31 13:22:52 LOG5[ui]: Compiled with OpenSSL 3.0.8 7 Feb 2023
2023.03.31 13:22:52 LOG5[ui]: Running  with OpenSSL 3.1.0 14 Mar 2023
2023.03.31 13:22:52 LOG5[ui]: Update OpenSSL shared libraries or rebuild stunnel
2023.03.31 13:22:52 LOG5[ui]: Threading:PTHREAD Sockets:POLL,IPv6 TLS:ENGINE,OCSP,PSK,SNI
2023.03.31 13:22:52 LOG5[ui]: Reading configuration from file /Users/cbusillo/VSCode/Shiny_API/shiny_api/config/stunnel.ini
2023.03.31 13:22:52 LOG5[ui]: UTF-8 byte order mark not detected
2023.03.31 13:22:52 LOG5[ui]: FIPS mode disabled
2023.03.31 13:22:52 LOG4[ui]: Insecure file permissions on /Users/cbusillo/.secret.privkey.pem
2023.03.31 13:22:52 LOG3[ui]: No trusted certificates found
2023.03.31 13:22:52 LOG5[ui]: Configuration successful
2023.03.31 13:22:52 LOG5[ui]: Binding service [https] to 0.0.0.0:8443: Address already in use (48)
2023.03.31 13:22:54 LOG5[ui]: Terminated
2023.03.31 13:22:54 LOG5[ui]: stunnel 5.69 on aarch64-apple-darwin22.3.0 platform
2023.03.31 13:22:54 LOG5[ui]: Compiled with OpenSSL 3.0.8 7 Feb 2023
2023.03.31 13:22:54 LOG5[ui]: Running  with OpenSSL 3.1.0 14 Mar 2023
2023.03.31 13:22:54 LOG5[ui]: Update OpenSSL shared libraries or rebuild stunnel
2023.03.31 13:22:54 LOG5[ui]: Threading:PTHREAD Sockets:POLL,IPv6 TLS:ENGINE,OCSP,PSK,SNI
2023.03.31 13:22:54 LOG5[ui]: Reading configuration from file /Users/cbusillo/VSCode/Shiny_API/shiny_api/config/stunnel.ini
2023.03.31 13:22:54 LOG5[ui]: UTF-8 byte order mark not detected
2023.03.31 13:22:54 LOG5[ui]: FIPS mode disabled
2023.03.31 13:22:54 LOG4[ui]: Insecure file permissions on /Users/cbusillo/.secret.privkey.pem
2023.03.31 13:22:54 LOG3[ui]: No trusted certificates found
2023.03.31 13:22:54 LOG5[ui]: Configuration successful
2023.03.31 13:22:54 LOG5[ui]: Binding service [https] to 0.0.0.0:8443: Address already in use (48)
2023.03.31 13:23:05 LOG3[ui]: Received SIGINT; terminating
2023.03.31 13:24:00 LOG5[ui]: stunnel 5.69 on aarch64-apple-darwin22.3.0 platform
2023.03.31 13:24:00 LOG5[ui]: Compiled with OpenSSL 3.0.8 7 Feb 2023
2023.03.31 13:24:00 LOG5[ui]: Running  with OpenSSL 3.1.0 14 Mar 2023
2023.03.31 13:24:00 LOG5[ui]: Update OpenSSL shared libraries or rebuild stunnel
2023.03.31 13:24:00 LOG5[ui]: Threading:PTHREAD Sockets:POLL,IPv6 TLS:ENGINE,OCSP,PSK,SNI
2023.03.31 13:24:00 LOG5[ui]: Reading configuration from file /Users/cbusillo/VSCode/Shiny_API/shiny_api/config/stunnel.ini
2023.03.31 13:24:00 LOG5[ui]: UTF-8 byte order mark not detected
2023.03.31 13:24:00 LOG5[ui]: FIPS mode disabled
2023.03.31 13:24:00 LOG4[ui]: Insecure file permissions on /Users/cbusillo/.secret.privkey.pem
2023.03.31 13:24:00 LOG3[ui]: No trusted certificates found
2023.03.31 13:24:00 LOG5[ui]: Configuration successful
2023.03.31 13:24:00 LOG5[ui]: Binding service [https] to 0.0.0.0:8000: Address already in use (48)
2023.03.31 13:24:02 LOG5[ui]: Terminated
2023.03.31 13:24:02 LOG5[ui]: stunnel 5.69 on aarch64-apple-darwin22.3.0 platform
2023.03.31 13:24:02 LOG5[ui]: Compiled with OpenSSL 3.0.8 7 Feb 2023
2023.03.31 13:24:02 LOG5[ui]: Running  with OpenSSL 3.1.0 14 Mar 2023
2023.03.31 13:24:02 LOG5[ui]: Update OpenSSL shared libraries or rebuild stunnel
2023.03.31 13:24:02 LOG5[ui]: Threading:PTHREAD Sockets:POLL,IPv6 TLS:ENGINE,OCSP,PSK,SNI
2023.03.31 13:24:02 LOG5[ui]: Reading configuration from file /Users/cbusillo/VSCode/Shiny_API/shiny_api/config/stunnel.ini
2023.03.31 13:24:02 LOG5[ui]: UTF-8 byte order mark not detected
2023.03.31 13:24:02 LOG5[ui]: FIPS mode disabled
2023.03.31 13:24:02 LOG4[ui]: Insecure file permissions on /Users/cbusillo/.secret.privkey.pem
2023.03.31 13:24:02 LOG3[ui]: No trusted certificates found
2023.03.31 13:24:02 LOG5[ui]: Configuration successful
2023.03.31 13:24:02 LOG5[ui]: Binding service [https] to 0.0.0.0:8000: Address already in use (48)
2023.03.31 13:24:09 LOG5[0]: Service [https] accepted connection from ::ffff:127.0.0.1:65225
2023.03.31 13:24:09 LOG3[0]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:24:09 LOG5[0]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:24:09 LOG5[0]: Service [https] connected remote server from 127.0.0.1:65227
2023.03.31 13:24:09 LOG5[1]: Service [https] accepted connection from ::ffff:127.0.0.1:65228
2023.03.31 13:24:09 LOG3[1]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:24:09 LOG5[1]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:24:09 LOG5[1]: Service [https] connected remote server from 127.0.0.1:65230
2023.03.31 13:24:10 LOG5[2]: Service [https] accepted connection from ::ffff:127.0.0.1:65231
2023.03.31 13:24:10 LOG3[2]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:24:10 LOG5[2]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:24:10 LOG5[2]: Service [https] connected remote server from 127.0.0.1:65233
2023.03.31 13:24:10 LOG5[3]: Service [https] accepted connection from ::ffff:127.0.0.1:65234
2023.03.31 13:24:10 LOG3[3]: SSL_accept: ssl/record/ssl3_record.c:345: error:0A00009C:SSL routines::http request
2023.03.31 13:24:10 LOG5[3]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:24:10 LOG5[4]: Service [https] accepted connection from ::ffff:127.0.0.1:65235
2023.03.31 13:24:10 LOG3[4]: SSL_accept: ssl/record/ssl3_record.c:345: error:0A00009C:SSL routines::http request
2023.03.31 13:24:10 LOG5[4]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:24:10 LOG5[5]: Service [https] accepted connection from ::ffff:127.0.0.1:65236
2023.03.31 13:24:10 LOG3[5]: SSL_accept: ssl/record/ssl3_record.c:345: error:0A00009C:SSL routines::http request
2023.03.31 13:24:10 LOG5[5]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:24:40 LOG5[1]: Connection closed: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:25:11 LOG5[0]: Connection closed: 22490 byte(s) sent to TLS, 3566 byte(s) sent to socket
2023.03.31 13:25:11 LOG5[2]: Connection closed: 3747 byte(s) sent to TLS, 1587 byte(s) sent to socket
2023.03.31 13:25:26 LOG5[6]: Service [https] accepted connection from ::ffff:127.0.0.1:65257
2023.03.31 13:25:26 LOG3[6]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:25:26 LOG5[6]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:25:26 LOG5[6]: Service [https] connected remote server from 127.0.0.1:65259
2023.03.31 13:25:26 LOG5[7]: Service [https] accepted connection from ::ffff:127.0.0.1:65260
2023.03.31 13:25:26 LOG3[7]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:25:26 LOG5[7]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:25:26 LOG5[7]: Service [https] connected remote server from 127.0.0.1:65262
2023.03.31 13:25:27 LOG5[8]: Service [https] accepted connection from ::ffff:127.0.0.1:65265
2023.03.31 13:25:27 LOG3[8]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:25:27 LOG5[8]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:25:27 LOG5[8]: Service [https] connected remote server from 127.0.0.1:65267
2023.03.31 13:25:57 LOG5[6]: Connection closed: 5240 byte(s) sent to TLS, 1234 byte(s) sent to socket
2023.03.31 13:26:27 LOG5[8]: Connection closed: 1249 byte(s) sent to TLS, 529 byte(s) sent to socket
2023.03.31 13:27:25 LOG5[7]: Connection closed: 366 byte(s) sent to TLS, 918 byte(s) sent to socket
2023.03.31 13:27:27 LOG5[ui]: Terminated
2023.03.31 13:27:27 LOG5[ui]: stunnel 5.69 on aarch64-apple-darwin22.3.0 platform
2023.03.31 13:27:27 LOG5[ui]: Compiled with OpenSSL 3.0.8 7 Feb 2023
2023.03.31 13:27:27 LOG5[ui]: Running  with OpenSSL 3.1.0 14 Mar 2023
2023.03.31 13:27:27 LOG5[ui]: Update OpenSSL shared libraries or rebuild stunnel
2023.03.31 13:27:27 LOG5[ui]: Threading:PTHREAD Sockets:POLL,IPv6 TLS:ENGINE,OCSP,PSK,SNI
2023.03.31 13:27:27 LOG5[ui]: Reading configuration from file /Users/cbusillo/VSCode/Shiny_API/shiny_api/config/stunnel.ini
2023.03.31 13:27:27 LOG5[ui]: UTF-8 byte order mark not detected
2023.03.31 13:27:27 LOG5[ui]: FIPS mode disabled
2023.03.31 13:27:27 LOG4[ui]: Insecure file permissions on /Users/cbusillo/.secret.privkey.pem
2023.03.31 13:27:27 LOG3[ui]: No trusted certificates found
2023.03.31 13:27:27 LOG5[ui]: Configuration successful
2023.03.31 13:27:27 LOG5[ui]: Binding service [https] to 0.0.0.0:8000: Address already in use (48)
2023.03.31 13:27:56 LOG5[ui]: stunnel 5.69 on aarch64-apple-darwin22.3.0 platform
2023.03.31 13:27:56 LOG5[ui]: Compiled with OpenSSL 3.0.8 7 Feb 2023
2023.03.31 13:27:56 LOG5[ui]: Running  with OpenSSL 3.1.0 14 Mar 2023
2023.03.31 13:27:56 LOG5[ui]: Update OpenSSL shared libraries or rebuild stunnel
2023.03.31 13:27:56 LOG5[ui]: Threading:PTHREAD Sockets:POLL,IPv6 TLS:ENGINE,OCSP,PSK,SNI
2023.03.31 13:27:56 LOG5[ui]: Reading configuration from file /Users/cbusillo/VSCode/Shiny_API/shiny_api/config/stunnel.ini
2023.03.31 13:27:56 LOG5[ui]: UTF-8 byte order mark not detected
2023.03.31 13:27:56 LOG5[ui]: FIPS mode disabled
2023.03.31 13:27:56 LOG4[ui]: Insecure file permissions on /Users/cbusillo/.secret.privkey.pem
2023.03.31 13:27:56 LOG3[ui]: No trusted certificates found
2023.03.31 13:27:56 LOG5[ui]: Configuration successful
2023.03.31 13:27:56 LOG5[ui]: Binding service [https] to 0.0.0.0:8000: Address already in use (48)
2023.03.31 13:27:59 LOG5[ui]: Terminated
2023.03.31 13:27:59 LOG5[ui]: stunnel 5.69 on aarch64-apple-darwin22.3.0 platform
2023.03.31 13:27:59 LOG5[ui]: Compiled with OpenSSL 3.0.8 7 Feb 2023
2023.03.31 13:27:59 LOG5[ui]: Running  with OpenSSL 3.1.0 14 Mar 2023
2023.03.31 13:27:59 LOG5[ui]: Update OpenSSL shared libraries or rebuild stunnel
2023.03.31 13:27:59 LOG5[ui]: Threading:PTHREAD Sockets:POLL,IPv6 TLS:ENGINE,OCSP,PSK,SNI
2023.03.31 13:27:59 LOG5[ui]: Reading configuration from file /Users/cbusillo/VSCode/Shiny_API/shiny_api/config/stunnel.ini
2023.03.31 13:27:59 LOG5[ui]: UTF-8 byte order mark not detected
2023.03.31 13:27:59 LOG5[ui]: FIPS mode disabled
2023.03.31 13:27:59 LOG4[ui]: Insecure file permissions on /Users/cbusillo/.secret.privkey.pem
2023.03.31 13:27:59 LOG3[ui]: No trusted certificates found
2023.03.31 13:27:59 LOG5[ui]: Configuration successful
2023.03.31 13:27:59 LOG5[ui]: Binding service [https] to 0.0.0.0:8000: Address already in use (48)
2023.03.31 13:28:08 LOG5[0]: Service [https] accepted connection from ::ffff:127.0.0.1:65342
2023.03.31 13:28:08 LOG3[0]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:28:08 LOG5[0]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:28:08 LOG5[0]: Service [https] connected remote server from 127.0.0.1:65344
2023.03.31 13:28:08 LOG5[1]: Service [https] accepted connection from ::ffff:127.0.0.1:65345
2023.03.31 13:28:08 LOG3[1]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:28:08 LOG5[1]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:28:08 LOG5[1]: Service [https] connected remote server from 127.0.0.1:65347
2023.03.31 13:28:09 LOG5[2]: Service [https] accepted connection from ::ffff:127.0.0.1:65350
2023.03.31 13:28:09 LOG3[2]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:28:09 LOG5[2]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:28:09 LOG5[2]: Service [https] connected remote server from 127.0.0.1:65352
2023.03.31 13:28:15 LOG5[1]: Connection closed: 445 byte(s) sent to TLS, 874 byte(s) sent to socket
2023.03.31 13:28:15 LOG5[3]: Service [https] accepted connection from ::ffff:127.0.0.1:65356
2023.03.31 13:28:15 LOG3[3]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:28:15 LOG5[3]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:28:15 LOG5[3]: Service [https] connected remote server from 127.0.0.1:65358
2023.03.31 13:29:02 LOG5[3]: Connection closed: 311 byte(s) sent to TLS, 786 byte(s) sent to socket
2023.03.31 13:29:02 LOG5[4]: Service [https] accepted connection from ::ffff:127.0.0.1:65373
2023.03.31 13:29:02 LOG3[4]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:29:02 LOG5[4]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:29:02 LOG5[4]: Service [https] connected remote server from 127.0.0.1:65375
2023.03.31 13:29:08 LOG5[4]: Connection closed: 367 byte(s) sent to TLS, 750 byte(s) sent to socket
2023.03.31 13:29:08 LOG5[5]: Service [https] accepted connection from ::ffff:127.0.0.1:65383
2023.03.31 13:29:08 LOG3[5]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:29:08 LOG5[5]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:29:08 LOG5[5]: Service [https] connected remote server from 127.0.0.1:65385
2023.03.31 13:29:40 LOG5[0]: Connection closed: 21460 byte(s) sent to TLS, 6335 byte(s) sent to socket
2023.03.31 13:29:40 LOG5[2]: Connection closed: 4996 byte(s) sent to TLS, 2116 byte(s) sent to socket
2023.03.31 13:30:07 LOG5[6]: Service [https] accepted connection from ::ffff:127.0.0.1:65418
2023.03.31 13:30:07 LOG5[7]: Service [https] accepted connection from ::ffff:127.0.0.1:65419
2023.03.31 13:30:07 LOG3[6]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:30:07 LOG5[6]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:30:07 LOG5[6]: Service [https] connected remote server from 127.0.0.1:65421
2023.03.31 13:30:07 LOG3[7]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:30:07 LOG5[7]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:30:07 LOG5[7]: Service [https] connected remote server from 127.0.0.1:65423
2023.03.31 13:30:07 LOG5[5]: Connection closed: 509 byte(s) sent to TLS, 786 byte(s) sent to socket
2023.03.31 13:30:07 LOG5[8]: Service [https] accepted connection from ::ffff:127.0.0.1:65425
2023.03.31 13:30:07 LOG3[8]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:30:07 LOG5[8]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:30:07 LOG5[8]: Service [https] connected remote server from 127.0.0.1:65427
2023.03.31 13:30:08 LOG5[9]: Service [https] accepted connection from ::ffff:127.0.0.1:65428
2023.03.31 13:30:08 LOG3[9]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:30:08 LOG5[9]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:30:08 LOG5[9]: Service [https] connected remote server from 127.0.0.1:65430
2023.03.31 13:30:12 LOG3[8]: readsocket: Connection reset by peer (54)
2023.03.31 13:30:12 LOG5[8]: Connection reset: 0 byte(s) sent to TLS, 742 byte(s) sent to socket
2023.03.31 13:30:12 LOG5[10]: Service [https] accepted connection from ::ffff:127.0.0.1:65432
2023.03.31 13:30:12 LOG3[10]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:30:12 LOG5[10]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:30:12 LOG5[10]: Service [https] connected remote server from 127.0.0.1:65434
2023.03.31 13:30:17 LOG3[10]: readsocket: Connection reset by peer (54)
2023.03.31 13:30:17 LOG5[10]: Connection reset: 0 byte(s) sent to TLS, 742 byte(s) sent to socket
2023.03.31 13:30:17 LOG5[11]: Service [https] accepted connection from ::ffff:127.0.0.1:65436
2023.03.31 13:30:17 LOG3[11]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:30:17 LOG5[11]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:30:17 LOG5[11]: Service [https] connected remote server from 127.0.0.1:65438
2023.03.31 13:30:22 LOG3[11]: readsocket: Connection reset by peer (54)
2023.03.31 13:30:22 LOG5[11]: Connection reset: 0 byte(s) sent to TLS, 742 byte(s) sent to socket
2023.03.31 13:30:38 LOG5[6]: Connection closed: 5240 byte(s) sent to TLS, 1233 byte(s) sent to socket
2023.03.31 13:30:38 LOG5[7]: Connection closed: 250 byte(s) sent to TLS, 701 byte(s) sent to socket
2023.03.31 13:31:08 LOG5[9]: Connection closed: 1249 byte(s) sent to TLS, 529 byte(s) sent to socket
2023.03.31 13:33:08 LOG5[12]: Service [https] accepted connection from ::ffff:127.0.0.1:65500
2023.03.31 13:33:08 LOG3[12]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:33:08 LOG3[12]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:33:08 LOG3[12]: No more addresses to connect
2023.03.31 13:33:08 LOG5[12]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:33:08 LOG5[13]: Service [https] accepted connection from ::ffff:127.0.0.1:65503
2023.03.31 13:33:08 LOG3[13]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:33:08 LOG3[13]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:33:08 LOG3[13]: No more addresses to connect
2023.03.31 13:33:08 LOG5[13]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:33:08 LOG5[14]: Service [https] accepted connection from ::ffff:127.0.0.1:65506
2023.03.31 13:33:08 LOG3[14]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:33:08 LOG3[14]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:33:08 LOG3[14]: No more addresses to connect
2023.03.31 13:33:08 LOG5[14]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:33:09 LOG5[ui]: Terminated
2023.03.31 13:33:09 LOG5[ui]: stunnel 5.69 on aarch64-apple-darwin22.3.0 platform
2023.03.31 13:33:09 LOG5[ui]: Compiled with OpenSSL 3.0.8 7 Feb 2023
2023.03.31 13:33:09 LOG5[ui]: Running  with OpenSSL 3.1.0 14 Mar 2023
2023.03.31 13:33:09 LOG5[ui]: Update OpenSSL shared libraries or rebuild stunnel
2023.03.31 13:33:09 LOG5[ui]: Threading:PTHREAD Sockets:POLL,IPv6 TLS:ENGINE,OCSP,PSK,SNI
2023.03.31 13:33:09 LOG5[ui]: Reading configuration from file /Users/cbusillo/VSCode/Shiny_API/shiny_api/config/stunnel.ini
2023.03.31 13:33:09 LOG5[ui]: UTF-8 byte order mark not detected
2023.03.31 13:33:09 LOG5[ui]: FIPS mode disabled
2023.03.31 13:33:09 LOG4[ui]: Insecure file permissions on /Users/cbusillo/.secret.privkey.pem
2023.03.31 13:33:09 LOG3[ui]: No trusted certificates found
2023.03.31 13:33:09 LOG5[ui]: Configuration successful
2023.03.31 13:33:09 LOG5[ui]: Binding service [https] to 0.0.0.0:8000: Address already in use (48)
2023.03.31 13:33:09 LOG5[0]: Service [https] accepted connection from ::ffff:127.0.0.1:65509
2023.03.31 13:33:09 LOG3[0]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:33:09 LOG3[0]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:33:09 LOG3[0]: No more addresses to connect
2023.03.31 13:33:09 LOG5[0]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:33:09 LOG5[1]: Service [https] accepted connection from ::ffff:127.0.0.1:65512
2023.03.31 13:33:09 LOG3[1]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:33:09 LOG3[1]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:33:09 LOG3[1]: No more addresses to connect
2023.03.31 13:33:09 LOG5[1]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:33:09 LOG5[2]: Service [https] accepted connection from ::ffff:127.0.0.1:65515
2023.03.31 13:33:09 LOG3[2]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:33:09 LOG3[2]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:33:09 LOG3[2]: No more addresses to connect
2023.03.31 13:33:09 LOG5[2]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:33:09 LOG5[3]: Service [https] accepted connection from ::ffff:127.0.0.1:65518
2023.03.31 13:33:09 LOG3[3]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:33:09 LOG3[3]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:33:09 LOG3[3]: No more addresses to connect
2023.03.31 13:33:09 LOG5[3]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:33:09 LOG5[4]: Service [https] accepted connection from ::ffff:127.0.0.1:65521
2023.03.31 13:33:09 LOG3[4]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:33:09 LOG3[4]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:33:09 LOG3[4]: No more addresses to connect
2023.03.31 13:33:09 LOG5[4]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:33:09 LOG5[5]: Service [https] accepted connection from ::ffff:127.0.0.1:65524
2023.03.31 13:33:09 LOG3[5]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:33:09 LOG3[5]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:33:09 LOG3[5]: No more addresses to connect
2023.03.31 13:33:09 LOG5[5]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:33:09 LOG5[6]: Service [https] accepted connection from ::ffff:127.0.0.1:65527
2023.03.31 13:33:09 LOG3[6]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:33:09 LOG3[6]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:33:09 LOG3[6]: No more addresses to connect
2023.03.31 13:33:09 LOG5[6]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:33:09 LOG5[7]: Service [https] accepted connection from ::ffff:127.0.0.1:65530
2023.03.31 13:33:09 LOG3[7]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:33:09 LOG3[7]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:33:09 LOG3[7]: No more addresses to connect
2023.03.31 13:33:09 LOG5[7]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:33:10 LOG5[8]: Service [https] accepted connection from ::ffff:127.0.0.1:65533
2023.03.31 13:33:10 LOG3[8]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:33:10 LOG3[8]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:33:10 LOG3[8]: No more addresses to connect
2023.03.31 13:33:10 LOG5[8]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:33:10 LOG5[9]: Service [https] accepted connection from ::ffff:127.0.0.1:49152
2023.03.31 13:33:10 LOG3[9]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:33:10 LOG3[9]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:33:10 LOG3[9]: No more addresses to connect
2023.03.31 13:33:10 LOG5[9]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:33:10 LOG5[10]: Service [https] accepted connection from ::ffff:127.0.0.1:49155
2023.03.31 13:33:10 LOG3[10]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:33:10 LOG3[10]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:33:10 LOG3[10]: No more addresses to connect
2023.03.31 13:33:10 LOG5[10]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:33:10 LOG5[11]: Service [https] accepted connection from ::ffff:127.0.0.1:49158
2023.03.31 13:33:10 LOG3[11]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:33:10 LOG3[11]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:33:10 LOG3[11]: No more addresses to connect
2023.03.31 13:33:10 LOG5[11]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:33:11 LOG5[12]: Service [https] accepted connection from ::ffff:127.0.0.1:49162
2023.03.31 13:33:11 LOG3[12]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:33:11 LOG3[12]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:33:11 LOG3[12]: No more addresses to connect
2023.03.31 13:33:11 LOG5[12]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:33:11 LOG5[13]: Service [https] accepted connection from ::ffff:127.0.0.1:49165
2023.03.31 13:33:11 LOG3[13]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:33:11 LOG3[13]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:33:11 LOG3[13]: No more addresses to connect
2023.03.31 13:33:11 LOG5[13]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:33:11 LOG5[14]: Service [https] accepted connection from ::ffff:127.0.0.1:49168
2023.03.31 13:33:11 LOG3[14]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:33:11 LOG3[14]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:33:11 LOG3[14]: No more addresses to connect
2023.03.31 13:33:11 LOG5[14]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:33:14 LOG5[15]: Service [https] accepted connection from ::ffff:127.0.0.1:49172
2023.03.31 13:33:14 LOG3[15]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:33:14 LOG3[15]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:33:14 LOG3[15]: No more addresses to connect
2023.03.31 13:33:14 LOG5[15]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:33:14 LOG5[16]: Service [https] accepted connection from ::ffff:127.0.0.1:49175
2023.03.31 13:33:14 LOG3[16]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:33:14 LOG3[16]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:33:14 LOG3[16]: No more addresses to connect
2023.03.31 13:33:14 LOG5[16]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:33:14 LOG5[17]: Service [https] accepted connection from ::ffff:127.0.0.1:49178
2023.03.31 13:33:14 LOG3[17]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:33:14 LOG3[17]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:33:14 LOG3[17]: No more addresses to connect
2023.03.31 13:33:14 LOG5[17]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:33:14 LOG5[18]: Service [https] accepted connection from ::ffff:127.0.0.1:49181
2023.03.31 13:33:14 LOG3[18]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:33:14 LOG3[18]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:33:14 LOG3[18]: No more addresses to connect
2023.03.31 13:33:14 LOG5[18]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:33:14 LOG5[19]: Service [https] accepted connection from ::ffff:127.0.0.1:49184
2023.03.31 13:33:14 LOG3[19]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:33:14 LOG3[19]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:33:14 LOG3[19]: No more addresses to connect
2023.03.31 13:33:14 LOG5[19]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:33:15 LOG5[20]: Service [https] accepted connection from ::ffff:127.0.0.1:49189
2023.03.31 13:33:15 LOG3[20]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:33:15 LOG3[20]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:33:15 LOG3[20]: No more addresses to connect
2023.03.31 13:33:15 LOG5[20]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:33:15 LOG5[21]: Service [https] accepted connection from ::ffff:127.0.0.1:49192
2023.03.31 13:33:15 LOG3[21]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:33:15 LOG3[21]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:33:15 LOG3[21]: No more addresses to connect
2023.03.31 13:33:15 LOG5[21]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:33:15 LOG5[22]: Service [https] accepted connection from ::ffff:127.0.0.1:49195
2023.03.31 13:33:15 LOG3[22]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:33:15 LOG3[22]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:33:15 LOG3[22]: No more addresses to connect
2023.03.31 13:33:15 LOG5[22]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:33:20 LOG5[23]: Service [https] accepted connection from ::ffff:127.0.0.1:49206
2023.03.31 13:33:20 LOG3[23]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:33:20 LOG3[23]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:33:20 LOG3[23]: No more addresses to connect
2023.03.31 13:33:20 LOG5[23]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:33:20 LOG5[24]: Service [https] accepted connection from ::ffff:127.0.0.1:49209
2023.03.31 13:33:20 LOG3[24]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:33:20 LOG3[24]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:33:20 LOG3[24]: No more addresses to connect
2023.03.31 13:33:20 LOG5[24]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:33:20 LOG5[25]: Service [https] accepted connection from ::ffff:127.0.0.1:49212
2023.03.31 13:33:20 LOG3[25]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:33:20 LOG3[25]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:33:20 LOG3[25]: No more addresses to connect
2023.03.31 13:33:20 LOG5[25]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:33:20 LOG5[26]: Service [https] accepted connection from ::ffff:127.0.0.1:49215
2023.03.31 13:33:20 LOG3[26]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:33:20 LOG3[26]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:33:20 LOG3[26]: No more addresses to connect
2023.03.31 13:33:20 LOG5[26]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:33:20 LOG5[27]: Service [https] accepted connection from ::ffff:127.0.0.1:49218
2023.03.31 13:33:20 LOG3[27]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:33:20 LOG3[27]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:33:20 LOG3[27]: No more addresses to connect
2023.03.31 13:33:20 LOG5[27]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:33:20 LOG5[28]: Service [https] accepted connection from ::ffff:127.0.0.1:49224
2023.03.31 13:33:20 LOG3[28]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:33:20 LOG3[28]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:33:20 LOG3[28]: No more addresses to connect
2023.03.31 13:33:20 LOG5[28]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:33:20 LOG5[29]: Service [https] accepted connection from ::ffff:127.0.0.1:49227
2023.03.31 13:33:20 LOG3[29]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:33:20 LOG3[29]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:33:20 LOG3[29]: No more addresses to connect
2023.03.31 13:33:20 LOG5[29]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:33:20 LOG5[ui]: Terminated
2023.03.31 13:33:20 LOG5[ui]: stunnel 5.69 on aarch64-apple-darwin22.3.0 platform
2023.03.31 13:33:20 LOG5[ui]: Compiled with OpenSSL 3.0.8 7 Feb 2023
2023.03.31 13:33:20 LOG5[ui]: Running  with OpenSSL 3.1.0 14 Mar 2023
2023.03.31 13:33:20 LOG5[ui]: Update OpenSSL shared libraries or rebuild stunnel
2023.03.31 13:33:20 LOG5[ui]: Threading:PTHREAD Sockets:POLL,IPv6 TLS:ENGINE,OCSP,PSK,SNI
2023.03.31 13:33:20 LOG5[ui]: Reading configuration from file /Users/cbusillo/VSCode/Shiny_API/shiny_api/config/stunnel.ini
2023.03.31 13:33:20 LOG5[ui]: UTF-8 byte order mark not detected
2023.03.31 13:33:20 LOG5[ui]: FIPS mode disabled
2023.03.31 13:33:20 LOG4[ui]: Insecure file permissions on /Users/cbusillo/.secret.privkey.pem
2023.03.31 13:33:20 LOG3[ui]: No trusted certificates found
2023.03.31 13:33:20 LOG5[ui]: Configuration successful
2023.03.31 13:33:20 LOG5[ui]: Binding service [https] to 0.0.0.0:8000: Address already in use (48)
2023.03.31 13:33:21 LOG5[0]: Service [https] accepted connection from ::ffff:127.0.0.1:49231
2023.03.31 13:33:21 LOG3[0]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:33:21 LOG3[0]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:33:21 LOG3[0]: No more addresses to connect
2023.03.31 13:33:21 LOG5[0]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:33:21 LOG5[1]: Service [https] accepted connection from ::ffff:127.0.0.1:49234
2023.03.31 13:33:21 LOG3[1]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:33:21 LOG3[1]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:33:21 LOG3[1]: No more addresses to connect
2023.03.31 13:33:21 LOG5[1]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:33:21 LOG5[2]: Service [https] accepted connection from ::ffff:127.0.0.1:49237
2023.03.31 13:33:21 LOG3[2]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:33:21 LOG3[2]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:33:21 LOG3[2]: No more addresses to connect
2023.03.31 13:33:21 LOG5[2]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:33:21 LOG5[3]: Service [https] accepted connection from ::ffff:127.0.0.1:49242
2023.03.31 13:33:21 LOG3[3]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:33:21 LOG3[3]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:33:21 LOG3[3]: No more addresses to connect
2023.03.31 13:33:21 LOG5[3]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:33:21 LOG5[4]: Service [https] accepted connection from ::ffff:127.0.0.1:49245
2023.03.31 13:33:21 LOG3[4]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:33:21 LOG3[4]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:33:21 LOG3[4]: No more addresses to connect
2023.03.31 13:33:21 LOG5[4]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:33:21 LOG5[5]: Service [https] accepted connection from ::ffff:127.0.0.1:49248
2023.03.31 13:33:21 LOG3[5]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:33:21 LOG3[5]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:33:21 LOG3[5]: No more addresses to connect
2023.03.31 13:33:21 LOG5[5]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:33:21 LOG5[6]: Service [https] accepted connection from ::ffff:127.0.0.1:49251
2023.03.31 13:33:21 LOG3[6]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:33:21 LOG3[6]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:33:21 LOG3[6]: No more addresses to connect
2023.03.31 13:33:21 LOG5[6]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:33:21 LOG5[7]: Service [https] accepted connection from ::ffff:127.0.0.1:49254
2023.03.31 13:33:21 LOG3[7]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:33:21 LOG3[7]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:33:21 LOG3[7]: No more addresses to connect
2023.03.31 13:33:21 LOG5[7]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:33:22 LOG5[8]: Service [https] accepted connection from ::ffff:127.0.0.1:49258
2023.03.31 13:33:22 LOG3[8]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:33:22 LOG5[8]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:33:22 LOG5[8]: Service [https] connected remote server from 127.0.0.1:49260
2023.03.31 13:33:22 LOG5[9]: Service [https] accepted connection from ::ffff:127.0.0.1:49261
2023.03.31 13:33:22 LOG3[9]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:33:22 LOG5[9]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:33:22 LOG5[9]: Service [https] connected remote server from 127.0.0.1:49263
2023.03.31 13:33:22 LOG5[10]: Service [https] accepted connection from ::ffff:127.0.0.1:49264
2023.03.31 13:33:22 LOG3[10]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:33:22 LOG5[10]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:33:22 LOG5[10]: Service [https] connected remote server from 127.0.0.1:49266
2023.03.31 13:33:28 LOG5[10]: Connection closed: 367 byte(s) sent to TLS, 788 byte(s) sent to socket
2023.03.31 13:33:28 LOG5[11]: Service [https] accepted connection from ::ffff:127.0.0.1:49273
2023.03.31 13:33:28 LOG3[11]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:33:28 LOG5[11]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:33:28 LOG5[11]: Service [https] connected remote server from 127.0.0.1:49275
2023.03.31 13:34:51 LOG5[ui]: stunnel 5.69 on aarch64-apple-darwin22.3.0 platform
2023.03.31 13:34:51 LOG5[ui]: Compiled with OpenSSL 3.0.8 7 Feb 2023
2023.03.31 13:34:51 LOG5[ui]: Running  with OpenSSL 3.1.0 14 Mar 2023
2023.03.31 13:34:51 LOG5[ui]: Update OpenSSL shared libraries or rebuild stunnel
2023.03.31 13:34:51 LOG5[ui]: Threading:PTHREAD Sockets:POLL,IPv6 TLS:ENGINE,OCSP,PSK,SNI
2023.03.31 13:34:51 LOG5[ui]: Reading configuration from file /Users/cbusillo/VSCode/Shiny_API/shiny_api/config/stunnel.ini
2023.03.31 13:34:51 LOG5[ui]: UTF-8 byte order mark not detected
2023.03.31 13:34:51 LOG5[ui]: FIPS mode disabled
2023.03.31 13:34:51 LOG4[ui]: Insecure file permissions on /Users/cbusillo/.secret.privkey.pem
2023.03.31 13:34:51 LOG3[ui]: No trusted certificates found
2023.03.31 13:34:51 LOG5[ui]: Configuration successful
2023.03.31 13:34:51 LOG5[ui]: Binding service [https] to 0.0.0.0:8000: Address already in use (48)
2023.03.31 13:34:53 LOG5[ui]: Terminated
2023.03.31 13:34:53 LOG5[ui]: stunnel 5.69 on aarch64-apple-darwin22.3.0 platform
2023.03.31 13:34:53 LOG5[ui]: Compiled with OpenSSL 3.0.8 7 Feb 2023
2023.03.31 13:34:53 LOG5[ui]: Running  with OpenSSL 3.1.0 14 Mar 2023
2023.03.31 13:34:53 LOG5[ui]: Update OpenSSL shared libraries or rebuild stunnel
2023.03.31 13:34:53 LOG5[ui]: Threading:PTHREAD Sockets:POLL,IPv6 TLS:ENGINE,OCSP,PSK,SNI
2023.03.31 13:34:53 LOG5[ui]: Reading configuration from file /Users/cbusillo/VSCode/Shiny_API/shiny_api/config/stunnel.ini
2023.03.31 13:34:53 LOG5[ui]: UTF-8 byte order mark not detected
2023.03.31 13:34:53 LOG5[ui]: FIPS mode disabled
2023.03.31 13:34:53 LOG4[ui]: Insecure file permissions on /Users/cbusillo/.secret.privkey.pem
2023.03.31 13:34:53 LOG3[ui]: No trusted certificates found
2023.03.31 13:34:53 LOG5[ui]: Configuration successful
2023.03.31 13:34:53 LOG5[ui]: Binding service [https] to 0.0.0.0:8000: Address already in use (48)
2023.03.31 13:34:58 LOG5[0]: Service [https] accepted connection from ::ffff:127.0.0.1:49331
2023.03.31 13:34:58 LOG3[0]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:34:58 LOG5[0]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:34:58 LOG5[0]: Service [https] connected remote server from 127.0.0.1:49333
2023.03.31 13:34:58 LOG5[1]: Service [https] accepted connection from ::ffff:127.0.0.1:49334
2023.03.31 13:34:58 LOG3[1]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:34:58 LOG5[1]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:34:58 LOG5[1]: Service [https] connected remote server from 127.0.0.1:49336
2023.03.31 13:34:59 LOG5[2]: Service [https] accepted connection from ::ffff:127.0.0.1:49339
2023.03.31 13:34:59 LOG3[2]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:34:59 LOG5[2]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:34:59 LOG5[2]: Service [https] connected remote server from 127.0.0.1:49341
2023.03.31 13:35:00 LOG5[1]: Connection closed: 420 byte(s) sent to TLS, 750 byte(s) sent to socket
2023.03.31 13:35:00 LOG5[3]: Service [https] accepted connection from ::ffff:127.0.0.1:49346
2023.03.31 13:35:00 LOG3[3]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:35:00 LOG5[3]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:35:00 LOG5[3]: Service [https] connected remote server from 127.0.0.1:49348
2023.03.31 13:35:20 LOG5[0]: Connection closed: 10730 byte(s) sent to TLS, 3167 byte(s) sent to socket
2023.03.31 13:35:20 LOG5[2]: Connection closed: 2498 byte(s) sent to TLS, 1058 byte(s) sent to socket
2023.03.31 13:35:20 LOG5[3]: Connection closed: 218 byte(s) sent to TLS, 742 byte(s) sent to socket
2023.03.31 13:35:21 LOG5[ui]: Terminated
2023.03.31 13:35:22 LOG5[ui]: stunnel 5.69 on aarch64-apple-darwin22.3.0 platform
2023.03.31 13:35:22 LOG5[ui]: Compiled with OpenSSL 3.0.8 7 Feb 2023
2023.03.31 13:35:22 LOG5[ui]: Running  with OpenSSL 3.1.0 14 Mar 2023
2023.03.31 13:35:22 LOG5[ui]: Update OpenSSL shared libraries or rebuild stunnel
2023.03.31 13:35:22 LOG5[ui]: Threading:PTHREAD Sockets:POLL,IPv6 TLS:ENGINE,OCSP,PSK,SNI
2023.03.31 13:35:22 LOG5[ui]: Reading configuration from file /Users/cbusillo/VSCode/Shiny_API/shiny_api/config/stunnel.ini
2023.03.31 13:35:22 LOG5[ui]: UTF-8 byte order mark not detected
2023.03.31 13:35:22 LOG5[ui]: FIPS mode disabled
2023.03.31 13:35:22 LOG4[ui]: Insecure file permissions on /Users/cbusillo/.secret.privkey.pem
2023.03.31 13:35:22 LOG3[ui]: No trusted certificates found
2023.03.31 13:35:22 LOG5[ui]: Configuration successful
2023.03.31 13:35:22 LOG5[ui]: Binding service [https] to 0.0.0.0:8000: Address already in use (48)
2023.03.31 13:35:22 LOG5[0]: Service [https] accepted connection from ::ffff:127.0.0.1:49369
2023.03.31 13:35:22 LOG5[1]: Service [https] accepted connection from ::ffff:127.0.0.1:49370
2023.03.31 13:35:22 LOG3[0]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:35:22 LOG3[0]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:35:22 LOG3[0]: No more addresses to connect
2023.03.31 13:35:22 LOG5[0]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:35:22 LOG3[1]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:35:22 LOG3[1]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:35:22 LOG3[1]: No more addresses to connect
2023.03.31 13:35:22 LOG5[1]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:35:22 LOG5[2]: Service [https] accepted connection from ::ffff:127.0.0.1:49375
2023.03.31 13:35:22 LOG3[2]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:35:22 LOG3[2]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:35:22 LOG3[2]: No more addresses to connect
2023.03.31 13:35:22 LOG5[2]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:35:22 LOG5[3]: Service [https] accepted connection from ::ffff:127.0.0.1:49378
2023.03.31 13:35:22 LOG3[3]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:35:22 LOG3[3]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:35:22 LOG3[3]: No more addresses to connect
2023.03.31 13:35:22 LOG5[3]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:35:23 LOG5[4]: Service [https] accepted connection from ::ffff:127.0.0.1:49383
2023.03.31 13:35:23 LOG3[4]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:35:23 LOG5[4]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:35:23 LOG5[4]: Service [https] connected remote server from 127.0.0.1:49385
2023.03.31 13:35:24 LOG5[5]: Service [https] accepted connection from ::ffff:127.0.0.1:49386
2023.03.31 13:35:24 LOG3[5]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:35:24 LOG5[5]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:35:24 LOG5[5]: Service [https] connected remote server from 127.0.0.1:49388
2023.03.31 13:35:24 LOG5[6]: Service [https] accepted connection from ::ffff:127.0.0.1:49394
2023.03.31 13:35:24 LOG3[6]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:35:24 LOG5[6]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:35:24 LOG5[6]: Service [https] connected remote server from 127.0.0.1:49396
2023.03.31 13:35:27 LOG5[6]: Connection closed: 222 byte(s) sent to TLS, 788 byte(s) sent to socket
2023.03.31 13:35:27 LOG5[7]: Service [https] accepted connection from ::ffff:127.0.0.1:49400
2023.03.31 13:35:27 LOG3[7]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:35:27 LOG5[7]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:35:27 LOG5[7]: Service [https] connected remote server from 127.0.0.1:49402
2023.03.31 13:35:48 LOG5[7]: Connection closed: 236 byte(s) sent to TLS, 768 byte(s) sent to socket
2023.03.31 13:35:48 LOG5[8]: Service [https] accepted connection from ::ffff:127.0.0.1:49417
2023.03.31 13:35:48 LOG3[8]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:35:48 LOG5[8]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:35:48 LOG5[8]: Service [https] connected remote server from 127.0.0.1:49419
2023.03.31 13:35:50 LOG5[8]: Connection closed: 222 byte(s) sent to TLS, 750 byte(s) sent to socket
2023.03.31 13:35:50 LOG5[9]: Service [https] accepted connection from ::ffff:127.0.0.1:49421
2023.03.31 13:35:50 LOG3[9]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:35:50 LOG5[9]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:35:50 LOG5[9]: Service [https] connected remote server from 127.0.0.1:49423
2023.03.31 13:35:53 LOG5[9]: Connection closed: 222 byte(s) sent to TLS, 750 byte(s) sent to socket
2023.03.31 13:35:53 LOG5[10]: Service [https] accepted connection from ::ffff:127.0.0.1:49425
2023.03.31 13:35:53 LOG3[10]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:35:53 LOG5[10]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:35:53 LOG5[10]: Service [https] connected remote server from 127.0.0.1:49427
2023.03.31 13:36:05 LOG5[10]: Connection closed: 222 byte(s) sent to TLS, 750 byte(s) sent to socket
2023.03.31 13:36:05 LOG5[11]: Service [https] accepted connection from ::ffff:127.0.0.1:49433
2023.03.31 13:36:05 LOG3[11]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:36:05 LOG5[11]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:36:05 LOG5[11]: Service [https] connected remote server from 127.0.0.1:49435
2023.03.31 13:36:06 LOG5[11]: Connection closed: 222 byte(s) sent to TLS, 750 byte(s) sent to socket
2023.03.31 13:36:06 LOG5[12]: Service [https] accepted connection from ::ffff:127.0.0.1:49436
2023.03.31 13:36:06 LOG3[12]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:36:06 LOG5[12]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:36:06 LOG5[12]: Service [https] connected remote server from 127.0.0.1:49438
2023.03.31 13:36:19 LOG5[ui]: stunnel 5.69 on aarch64-apple-darwin22.3.0 platform
2023.03.31 13:36:19 LOG5[ui]: Compiled with OpenSSL 3.0.8 7 Feb 2023
2023.03.31 13:36:19 LOG5[ui]: Running  with OpenSSL 3.1.0 14 Mar 2023
2023.03.31 13:36:19 LOG5[ui]: Update OpenSSL shared libraries or rebuild stunnel
2023.03.31 13:36:19 LOG5[ui]: Threading:PTHREAD Sockets:POLL,IPv6 TLS:ENGINE,OCSP,PSK,SNI
2023.03.31 13:36:19 LOG5[ui]: Reading configuration from file /Users/cbusillo/VSCode/Shiny_API/shiny_api/config/stunnel.ini
2023.03.31 13:36:19 LOG5[ui]: UTF-8 byte order mark not detected
2023.03.31 13:36:19 LOG5[ui]: FIPS mode disabled
2023.03.31 13:36:19 LOG4[ui]: Insecure file permissions on /Users/cbusillo/.secret.privkey.pem
2023.03.31 13:36:19 LOG3[ui]: No trusted certificates found
2023.03.31 13:36:19 LOG5[ui]: Configuration successful
2023.03.31 13:36:19 LOG5[ui]: Binding service [https] to 0.0.0.0:8000: Address already in use (48)
2023.03.31 13:36:21 LOG5[0]: Service [https] accepted connection from ::ffff:127.0.0.1:49466
2023.03.31 13:36:21 LOG3[0]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:36:21 LOG3[0]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:36:21 LOG3[0]: No more addresses to connect
2023.03.31 13:36:21 LOG5[0]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:36:21 LOG5[1]: Service [https] accepted connection from ::ffff:127.0.0.1:49469
2023.03.31 13:36:21 LOG3[1]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:36:21 LOG3[1]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:36:21 LOG3[1]: No more addresses to connect
2023.03.31 13:36:21 LOG5[1]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:36:21 LOG5[2]: Service [https] accepted connection from ::ffff:127.0.0.1:49472
2023.03.31 13:36:21 LOG3[2]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:36:21 LOG3[2]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:36:21 LOG3[2]: No more addresses to connect
2023.03.31 13:36:21 LOG5[2]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:36:22 LOG5[ui]: Terminated
2023.03.31 13:36:22 LOG5[ui]: stunnel 5.69 on aarch64-apple-darwin22.3.0 platform
2023.03.31 13:36:22 LOG5[ui]: Compiled with OpenSSL 3.0.8 7 Feb 2023
2023.03.31 13:36:22 LOG5[ui]: Running  with OpenSSL 3.1.0 14 Mar 2023
2023.03.31 13:36:22 LOG5[ui]: Update OpenSSL shared libraries or rebuild stunnel
2023.03.31 13:36:22 LOG5[ui]: Threading:PTHREAD Sockets:POLL,IPv6 TLS:ENGINE,OCSP,PSK,SNI
2023.03.31 13:36:22 LOG5[ui]: Reading configuration from file /Users/cbusillo/VSCode/Shiny_API/shiny_api/config/stunnel.ini
2023.03.31 13:36:22 LOG5[ui]: UTF-8 byte order mark not detected
2023.03.31 13:36:22 LOG5[ui]: FIPS mode disabled
2023.03.31 13:36:22 LOG4[ui]: Insecure file permissions on /Users/cbusillo/.secret.privkey.pem
2023.03.31 13:36:22 LOG3[ui]: No trusted certificates found
2023.03.31 13:36:22 LOG5[ui]: Configuration successful
2023.03.31 13:36:22 LOG5[ui]: Binding service [https] to 0.0.0.0:8000: Address already in use (48)
2023.03.31 13:36:22 LOG5[0]: Service [https] accepted connection from ::ffff:127.0.0.1:49479
2023.03.31 13:36:22 LOG3[0]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:36:22 LOG3[0]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:36:22 LOG3[0]: No more addresses to connect
2023.03.31 13:36:22 LOG5[0]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:36:22 LOG5[1]: Service [https] accepted connection from ::ffff:127.0.0.1:49482
2023.03.31 13:36:22 LOG5[2]: Service [https] accepted connection from ::ffff:127.0.0.1:49483
2023.03.31 13:36:22 LOG3[1]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:36:22 LOG3[1]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:36:22 LOG3[1]: No more addresses to connect
2023.03.31 13:36:22 LOG5[1]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:36:22 LOG3[2]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:36:22 LOG3[2]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:36:22 LOG3[2]: No more addresses to connect
2023.03.31 13:36:22 LOG5[2]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:36:22 LOG5[3]: Service [https] accepted connection from ::ffff:127.0.0.1:49488
2023.03.31 13:36:22 LOG3[3]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:36:22 LOG3[3]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:36:22 LOG3[3]: No more addresses to connect
2023.03.31 13:36:22 LOG5[3]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:36:22 LOG5[4]: Service [https] accepted connection from ::ffff:127.0.0.1:49491
2023.03.31 13:36:22 LOG3[4]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:36:22 LOG3[4]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:36:22 LOG3[4]: No more addresses to connect
2023.03.31 13:36:22 LOG5[4]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:36:22 LOG5[5]: Service [https] accepted connection from ::ffff:127.0.0.1:49494
2023.03.31 13:36:22 LOG3[5]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:36:22 LOG3[5]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:36:22 LOG3[5]: No more addresses to connect
2023.03.31 13:36:22 LOG5[5]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:36:22 LOG5[6]: Service [https] accepted connection from ::ffff:127.0.0.1:49497
2023.03.31 13:36:22 LOG3[6]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:36:22 LOG3[6]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:36:22 LOG3[6]: No more addresses to connect
2023.03.31 13:36:22 LOG5[6]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:36:22 LOG5[7]: Service [https] accepted connection from ::ffff:127.0.0.1:49500
2023.03.31 13:36:22 LOG3[7]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:36:22 LOG3[7]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:36:22 LOG3[7]: No more addresses to connect
2023.03.31 13:36:22 LOG5[7]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:36:26 LOG5[8]: Service [https] accepted connection from ::ffff:127.0.0.1:49505
2023.03.31 13:36:26 LOG3[8]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:36:26 LOG5[8]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:36:26 LOG5[8]: Service [https] connected remote server from 127.0.0.1:49507
2023.03.31 13:36:26 LOG5[9]: Service [https] accepted connection from ::ffff:127.0.0.1:49513
2023.03.31 13:36:26 LOG3[9]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:36:26 LOG5[9]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:36:26 LOG5[9]: Service [https] connected remote server from 127.0.0.1:49515
2023.03.31 13:36:27 LOG5[10]: Service [https] accepted connection from ::ffff:127.0.0.1:49518
2023.03.31 13:36:27 LOG3[10]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:36:27 LOG5[10]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:36:27 LOG5[10]: Service [https] connected remote server from 127.0.0.1:49520
2023.03.31 13:37:02 LOG5[8]: Connection closed: 5490 byte(s) sent to TLS, 1798 byte(s) sent to socket
2023.03.31 13:37:02 LOG5[10]: Connection closed: 1249 byte(s) sent to TLS, 529 byte(s) sent to socket
2023.03.31 13:37:32 LOG5[9]: Connection closed: 260 byte(s) sent to TLS, 796 byte(s) sent to socket
2023.03.31 13:37:34 LOG5[ui]: Terminated
2023.03.31 13:37:34 LOG5[ui]: stunnel 5.69 on aarch64-apple-darwin22.3.0 platform
2023.03.31 13:37:34 LOG5[ui]: Compiled with OpenSSL 3.0.8 7 Feb 2023
2023.03.31 13:37:34 LOG5[ui]: Running  with OpenSSL 3.1.0 14 Mar 2023
2023.03.31 13:37:34 LOG5[ui]: Update OpenSSL shared libraries or rebuild stunnel
2023.03.31 13:37:34 LOG5[ui]: Threading:PTHREAD Sockets:POLL,IPv6 TLS:ENGINE,OCSP,PSK,SNI
2023.03.31 13:37:34 LOG5[ui]: Reading configuration from file /Users/cbusillo/VSCode/Shiny_API/shiny_api/config/stunnel.ini
2023.03.31 13:37:34 LOG5[ui]: UTF-8 byte order mark not detected
2023.03.31 13:37:34 LOG5[ui]: FIPS mode disabled
2023.03.31 13:37:34 LOG4[ui]: Insecure file permissions on /Users/cbusillo/.secret.privkey.pem
2023.03.31 13:37:34 LOG3[ui]: No trusted certificates found
2023.03.31 13:37:34 LOG5[ui]: Configuration successful
2023.03.31 13:37:34 LOG5[ui]: Binding service [https] to 0.0.0.0:8000: Address already in use (48)
2023.03.31 13:37:44 LOG5[ui]: stunnel 5.69 on aarch64-apple-darwin22.3.0 platform
2023.03.31 13:37:44 LOG5[ui]: Compiled with OpenSSL 3.0.8 7 Feb 2023
2023.03.31 13:37:44 LOG5[ui]: Running  with OpenSSL 3.1.0 14 Mar 2023
2023.03.31 13:37:44 LOG5[ui]: Update OpenSSL shared libraries or rebuild stunnel
2023.03.31 13:37:44 LOG5[ui]: Threading:PTHREAD Sockets:POLL,IPv6 TLS:ENGINE,OCSP,PSK,SNI
2023.03.31 13:37:44 LOG5[ui]: Reading configuration from file /Users/cbusillo/VSCode/Shiny_API/shiny_api/config/stunnel.ini
2023.03.31 13:37:44 LOG5[ui]: UTF-8 byte order mark not detected
2023.03.31 13:37:44 LOG5[ui]: FIPS mode disabled
2023.03.31 13:37:44 LOG4[ui]: Insecure file permissions on /Users/cbusillo/.secret.privkey.pem
2023.03.31 13:37:44 LOG3[ui]: No trusted certificates found
2023.03.31 13:37:44 LOG5[ui]: Configuration successful
2023.03.31 13:37:44 LOG5[ui]: Binding service [https] to 0.0.0.0:8000: Address already in use (48)
2023.03.31 13:37:46 LOG5[ui]: Terminated
2023.03.31 13:37:46 LOG5[ui]: stunnel 5.69 on aarch64-apple-darwin22.3.0 platform
2023.03.31 13:37:46 LOG5[ui]: Compiled with OpenSSL 3.0.8 7 Feb 2023
2023.03.31 13:37:46 LOG5[ui]: Running  with OpenSSL 3.1.0 14 Mar 2023
2023.03.31 13:37:46 LOG5[ui]: Update OpenSSL shared libraries or rebuild stunnel
2023.03.31 13:37:46 LOG5[ui]: Threading:PTHREAD Sockets:POLL,IPv6 TLS:ENGINE,OCSP,PSK,SNI
2023.03.31 13:37:46 LOG5[ui]: Reading configuration from file /Users/cbusillo/VSCode/Shiny_API/shiny_api/config/stunnel.ini
2023.03.31 13:37:46 LOG5[ui]: UTF-8 byte order mark not detected
2023.03.31 13:37:46 LOG5[ui]: FIPS mode disabled
2023.03.31 13:37:46 LOG4[ui]: Insecure file permissions on /Users/cbusillo/.secret.privkey.pem
2023.03.31 13:37:46 LOG3[ui]: No trusted certificates found
2023.03.31 13:37:46 LOG5[ui]: Configuration successful
2023.03.31 13:37:46 LOG5[ui]: Binding service [https] to 0.0.0.0:8000: Address already in use (48)
2023.03.31 13:38:36 LOG5[1]: Service [https] accepted connection from ::ffff:127.0.0.1:49595
2023.03.31 13:38:36 LOG5[0]: Service [https] accepted connection from ::ffff:127.0.0.1:49594
2023.03.31 13:38:36 LOG3[0]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:38:36 LOG5[0]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:38:36 LOG5[0]: Service [https] connected remote server from 127.0.0.1:49597
2023.03.31 13:38:36 LOG3[1]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:38:36 LOG5[1]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:38:36 LOG5[1]: Service [https] connected remote server from 127.0.0.1:49599
2023.03.31 13:38:37 LOG5[2]: Service [https] accepted connection from ::ffff:127.0.0.1:49604
2023.03.31 13:38:37 LOG3[2]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:38:37 LOG5[2]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:38:37 LOG5[2]: Service [https] connected remote server from 127.0.0.1:49607
2023.03.31 13:38:37 LOG5[3]: Service [https] accepted connection from ::ffff:127.0.0.1:49610
2023.03.31 13:38:37 LOG3[3]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:38:37 LOG5[3]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:38:37 LOG5[3]: Service [https] connected remote server from 127.0.0.1:49612
2023.03.31 13:39:07 LOG5[0]: Connection closed: 5240 byte(s) sent to TLS, 1233 byte(s) sent to socket
2023.03.31 13:39:07 LOG5[1]: Connection closed: 250 byte(s) sent to TLS, 701 byte(s) sent to socket
2023.03.31 13:39:12 LOG5[4]: Service [https] accepted connection from ::ffff:127.0.0.1:49630
2023.03.31 13:39:12 LOG3[4]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:39:12 LOG5[4]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:39:12 LOG5[4]: Service [https] connected remote server from 127.0.0.1:49632
2023.03.31 13:39:12 LOG5[2]: Connection closed: 236 byte(s) sent to TLS, 768 byte(s) sent to socket
2023.03.31 13:39:12 LOG5[5]: Service [https] accepted connection from ::ffff:127.0.0.1:49633
2023.03.31 13:39:12 LOG3[5]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:39:12 LOG5[5]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:39:12 LOG5[5]: Service [https] connected remote server from 127.0.0.1:49635
2023.03.31 13:39:13 LOG5[5]: Connection closed: 367 byte(s) sent to TLS, 750 byte(s) sent to socket
2023.03.31 13:39:13 LOG5[6]: Service [https] accepted connection from ::ffff:127.0.0.1:49640
2023.03.31 13:39:13 LOG3[6]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:39:13 LOG5[6]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:39:13 LOG5[6]: Service [https] connected remote server from 127.0.0.1:49642
2023.03.31 13:39:25 LOG5[ui]: stunnel 5.69 on aarch64-apple-darwin22.3.0 platform
2023.03.31 13:39:25 LOG5[ui]: Compiled with OpenSSL 3.0.8 7 Feb 2023
2023.03.31 13:39:25 LOG5[ui]: Running  with OpenSSL 3.1.0 14 Mar 2023
2023.03.31 13:39:25 LOG5[ui]: Update OpenSSL shared libraries or rebuild stunnel
2023.03.31 13:39:25 LOG5[ui]: Threading:PTHREAD Sockets:POLL,IPv6 TLS:ENGINE,OCSP,PSK,SNI
2023.03.31 13:39:25 LOG5[ui]: Reading configuration from file /Users/cbusillo/VSCode/Shiny_API/shiny_api/config/stunnel.ini
2023.03.31 13:39:25 LOG5[ui]: UTF-8 byte order mark not detected
2023.03.31 13:39:25 LOG5[ui]: FIPS mode disabled
2023.03.31 13:39:25 LOG4[ui]: Insecure file permissions on /Users/cbusillo/.secret.privkey.pem
2023.03.31 13:39:25 LOG3[ui]: No trusted certificates found
2023.03.31 13:39:25 LOG5[ui]: Configuration successful
2023.03.31 13:39:25 LOG5[ui]: Binding service [https] to 0.0.0.0:8000: Address already in use (48)
2023.03.31 13:39:28 LOG5[ui]: Terminated
2023.03.31 13:39:28 LOG5[ui]: stunnel 5.69 on aarch64-apple-darwin22.3.0 platform
2023.03.31 13:39:28 LOG5[ui]: Compiled with OpenSSL 3.0.8 7 Feb 2023
2023.03.31 13:39:28 LOG5[ui]: Running  with OpenSSL 3.1.0 14 Mar 2023
2023.03.31 13:39:28 LOG5[ui]: Update OpenSSL shared libraries or rebuild stunnel
2023.03.31 13:39:28 LOG5[ui]: Threading:PTHREAD Sockets:POLL,IPv6 TLS:ENGINE,OCSP,PSK,SNI
2023.03.31 13:39:28 LOG5[ui]: Reading configuration from file /Users/cbusillo/VSCode/Shiny_API/shiny_api/config/stunnel.ini
2023.03.31 13:39:28 LOG5[ui]: UTF-8 byte order mark not detected
2023.03.31 13:39:28 LOG5[ui]: FIPS mode disabled
2023.03.31 13:39:28 LOG4[ui]: Insecure file permissions on /Users/cbusillo/.secret.privkey.pem
2023.03.31 13:39:28 LOG3[ui]: No trusted certificates found
2023.03.31 13:39:28 LOG5[ui]: Configuration successful
2023.03.31 13:39:28 LOG5[ui]: Binding service [https] to 0.0.0.0:8000: Address already in use (48)
2023.03.31 13:39:31 LOG5[0]: Service [https] accepted connection from ::ffff:127.0.0.1:49669
2023.03.31 13:39:31 LOG3[0]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:39:31 LOG5[0]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:39:31 LOG5[0]: Service [https] connected remote server from 127.0.0.1:49671
2023.03.31 13:39:31 LOG5[1]: Service [https] accepted connection from ::ffff:127.0.0.1:49672
2023.03.31 13:39:31 LOG3[1]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:39:31 LOG5[1]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:39:31 LOG5[1]: Service [https] connected remote server from 127.0.0.1:49674
2023.03.31 13:39:32 LOG5[2]: Service [https] accepted connection from ::ffff:127.0.0.1:49677
2023.03.31 13:39:32 LOG3[2]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:39:32 LOG5[2]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:39:32 LOG5[2]: Service [https] connected remote server from 127.0.0.1:49679
2023.03.31 13:39:36 LOG5[1]: Connection closed: 420 byte(s) sent to TLS, 750 byte(s) sent to socket
2023.03.31 13:39:36 LOG5[3]: Service [https] accepted connection from ::ffff:127.0.0.1:49685
2023.03.31 13:39:36 LOG3[3]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:39:36 LOG5[3]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:39:36 LOG5[3]: Service [https] connected remote server from 127.0.0.1:49688
2023.03.31 13:39:44 LOG5[3]: Connection closed: 222 byte(s) sent to TLS, 750 byte(s) sent to socket
2023.03.31 13:39:44 LOG5[4]: Service [https] accepted connection from ::ffff:127.0.0.1:49693
2023.03.31 13:39:44 LOG3[4]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:39:44 LOG5[4]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:39:44 LOG5[4]: Service [https] connected remote server from 127.0.0.1:49695
2023.03.31 13:39:45 LOG5[4]: Connection closed: 275 byte(s) sent to TLS, 750 byte(s) sent to socket
2023.03.31 13:39:45 LOG5[5]: Service [https] accepted connection from ::ffff:127.0.0.1:49700
2023.03.31 13:39:45 LOG3[5]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:39:45 LOG5[5]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:39:45 LOG5[5]: Service [https] connected remote server from 127.0.0.1:49702
2023.03.31 13:39:52 LOG5[ui]: stunnel 5.69 on aarch64-apple-darwin22.3.0 platform
2023.03.31 13:39:52 LOG5[ui]: Compiled with OpenSSL 3.0.8 7 Feb 2023
2023.03.31 13:39:52 LOG5[ui]: Running  with OpenSSL 3.1.0 14 Mar 2023
2023.03.31 13:39:52 LOG5[ui]: Update OpenSSL shared libraries or rebuild stunnel
2023.03.31 13:39:52 LOG5[ui]: Threading:PTHREAD Sockets:POLL,IPv6 TLS:ENGINE,OCSP,PSK,SNI
2023.03.31 13:39:52 LOG5[ui]: Reading configuration from file /Users/cbusillo/VSCode/Shiny_API/shiny_api/config/stunnel.ini
2023.03.31 13:39:52 LOG5[ui]: UTF-8 byte order mark not detected
2023.03.31 13:39:52 LOG5[ui]: FIPS mode disabled
2023.03.31 13:39:52 LOG4[ui]: Insecure file permissions on /Users/cbusillo/.secret.privkey.pem
2023.03.31 13:39:52 LOG3[ui]: No trusted certificates found
2023.03.31 13:39:52 LOG5[ui]: Configuration successful
2023.03.31 13:39:52 LOG5[ui]: Binding service [https] to 0.0.0.0:8000: Address already in use (48)
2023.03.31 13:39:54 LOG5[ui]: Terminated
2023.03.31 13:39:54 LOG5[ui]: stunnel 5.69 on aarch64-apple-darwin22.3.0 platform
2023.03.31 13:39:54 LOG5[ui]: Compiled with OpenSSL 3.0.8 7 Feb 2023
2023.03.31 13:39:54 LOG5[ui]: Running  with OpenSSL 3.1.0 14 Mar 2023
2023.03.31 13:39:54 LOG5[ui]: Update OpenSSL shared libraries or rebuild stunnel
2023.03.31 13:39:54 LOG5[ui]: Threading:PTHREAD Sockets:POLL,IPv6 TLS:ENGINE,OCSP,PSK,SNI
2023.03.31 13:39:54 LOG5[ui]: Reading configuration from file /Users/cbusillo/VSCode/Shiny_API/shiny_api/config/stunnel.ini
2023.03.31 13:39:54 LOG5[ui]: UTF-8 byte order mark not detected
2023.03.31 13:39:54 LOG5[ui]: FIPS mode disabled
2023.03.31 13:39:54 LOG4[ui]: Insecure file permissions on /Users/cbusillo/.secret.privkey.pem
2023.03.31 13:39:54 LOG3[ui]: No trusted certificates found
2023.03.31 13:39:54 LOG5[ui]: Configuration successful
2023.03.31 13:39:54 LOG5[ui]: Binding service [https] to 0.0.0.0:8000: Address already in use (48)
2023.03.31 13:39:57 LOG5[0]: Service [https] accepted connection from ::ffff:127.0.0.1:49727
2023.03.31 13:39:57 LOG3[0]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:39:57 LOG5[0]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:39:57 LOG5[0]: Service [https] connected remote server from 127.0.0.1:49729
2023.03.31 13:39:58 LOG5[1]: Service [https] accepted connection from ::ffff:127.0.0.1:49730
2023.03.31 13:39:58 LOG3[1]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:39:58 LOG5[1]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:39:58 LOG5[1]: Service [https] connected remote server from 127.0.0.1:49732
2023.03.31 13:39:58 LOG5[2]: Service [https] accepted connection from ::ffff:127.0.0.1:49735
2023.03.31 13:39:58 LOG3[2]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:39:58 LOG5[2]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:39:58 LOG5[2]: Service [https] connected remote server from 127.0.0.1:49737
2023.03.31 13:40:35 LOG5[1]: Connection closed: 236 byte(s) sent to TLS, 768 byte(s) sent to socket
2023.03.31 13:40:35 LOG5[3]: Service [https] accepted connection from ::ffff:127.0.0.1:49749
2023.03.31 13:40:35 LOG3[3]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:40:35 LOG5[3]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:40:35 LOG5[3]: Service [https] connected remote server from 127.0.0.1:49751
2023.03.31 13:40:37 LOG5[3]: Connection closed: 222 byte(s) sent to TLS, 788 byte(s) sent to socket
2023.03.31 13:40:37 LOG5[4]: Service [https] accepted connection from ::ffff:127.0.0.1:49756
2023.03.31 13:40:37 LOG3[4]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:40:37 LOG5[4]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:40:37 LOG5[4]: Service [https] connected remote server from 127.0.0.1:49758
2023.03.31 13:41:10 LOG5[2]: Connection closed: 3747 byte(s) sent to TLS, 1587 byte(s) sent to socket
2023.03.31 13:41:10 LOG5[5]: Service [https] accepted connection from ::ffff:127.0.0.1:49778
2023.03.31 13:41:10 LOG3[5]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:41:10 LOG5[5]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:41:10 LOG5[5]: Service [https] connected remote server from 127.0.0.1:49780
2023.03.31 13:41:13 LOG5[4]: Connection closed: 442 byte(s) sent to TLS, 768 byte(s) sent to socket
2023.03.31 13:41:13 LOG5[6]: Service [https] accepted connection from ::ffff:127.0.0.1:49782
2023.03.31 13:41:13 LOG3[6]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:41:13 LOG5[6]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:41:13 LOG5[6]: Service [https] connected remote server from 127.0.0.1:49784
2023.03.31 13:41:41 LOG5[5]: Connection closed: 1249 byte(s) sent to TLS, 529 byte(s) sent to socket
2023.03.31 13:41:47 LOG5[0]: Connection closed: 21460 byte(s) sent to TLS, 6198 byte(s) sent to socket
2023.03.31 13:44:42 LOG5[6]: Connection closed: 419 byte(s) sent to TLS, 922 byte(s) sent to socket
2023.03.31 13:44:44 LOG5[ui]: Terminated
2023.03.31 13:44:44 LOG5[ui]: stunnel 5.69 on aarch64-apple-darwin22.3.0 platform
2023.03.31 13:44:44 LOG5[ui]: Compiled with OpenSSL 3.0.8 7 Feb 2023
2023.03.31 13:44:44 LOG5[ui]: Running  with OpenSSL 3.1.0 14 Mar 2023
2023.03.31 13:44:44 LOG5[ui]: Update OpenSSL shared libraries or rebuild stunnel
2023.03.31 13:44:44 LOG5[ui]: Threading:PTHREAD Sockets:POLL,IPv6 TLS:ENGINE,OCSP,PSK,SNI
2023.03.31 13:44:44 LOG5[ui]: Reading configuration from file /Users/cbusillo/VSCode/Shiny_API/shiny_api/config/stunnel.ini
2023.03.31 13:44:44 LOG5[ui]: UTF-8 byte order mark not detected
2023.03.31 13:44:44 LOG5[ui]: FIPS mode disabled
2023.03.31 13:44:44 LOG4[ui]: Insecure file permissions on /Users/cbusillo/.secret.privkey.pem
2023.03.31 13:44:44 LOG3[ui]: No trusted certificates found
2023.03.31 13:44:44 LOG5[ui]: Configuration successful
2023.03.31 13:44:44 LOG5[ui]: Binding service [https] to 0.0.0.0:8000: Address already in use (48)
2023.03.31 13:45:04 LOG5[0]: Service [https] accepted connection from ::ffff:127.0.0.1:49894
2023.03.31 13:45:04 LOG3[0]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:45:04 LOG3[0]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:45:04 LOG3[0]: No more addresses to connect
2023.03.31 13:45:04 LOG5[0]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:45:04 LOG5[1]: Service [https] accepted connection from ::ffff:127.0.0.1:49897
2023.03.31 13:45:04 LOG3[1]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:45:04 LOG3[1]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:45:04 LOG3[1]: No more addresses to connect
2023.03.31 13:45:04 LOG5[1]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:45:04 LOG5[ui]: Terminated
2023.03.31 13:45:04 LOG5[ui]: stunnel 5.69 on aarch64-apple-darwin22.3.0 platform
2023.03.31 13:45:04 LOG5[ui]: Compiled with OpenSSL 3.0.8 7 Feb 2023
2023.03.31 13:45:04 LOG5[ui]: Running  with OpenSSL 3.1.0 14 Mar 2023
2023.03.31 13:45:04 LOG5[ui]: Update OpenSSL shared libraries or rebuild stunnel
2023.03.31 13:45:04 LOG5[ui]: Threading:PTHREAD Sockets:POLL,IPv6 TLS:ENGINE,OCSP,PSK,SNI
2023.03.31 13:45:04 LOG5[ui]: Reading configuration from file /Users/cbusillo/VSCode/Shiny_API/shiny_api/config/stunnel.ini
2023.03.31 13:45:04 LOG5[ui]: UTF-8 byte order mark not detected
2023.03.31 13:45:04 LOG5[ui]: FIPS mode disabled
2023.03.31 13:45:04 LOG4[ui]: Insecure file permissions on /Users/cbusillo/.secret.privkey.pem
2023.03.31 13:45:04 LOG3[ui]: No trusted certificates found
2023.03.31 13:45:04 LOG5[ui]: Configuration successful
2023.03.31 13:45:04 LOG5[ui]: Binding service [https] to 0.0.0.0:8000: Address already in use (48)
2023.03.31 13:45:05 LOG5[0]: Service [https] accepted connection from ::ffff:127.0.0.1:49900
2023.03.31 13:45:05 LOG3[0]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:45:05 LOG3[0]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:45:05 LOG3[0]: No more addresses to connect
2023.03.31 13:45:05 LOG5[0]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:45:05 LOG5[1]: Service [https] accepted connection from ::ffff:127.0.0.1:49906
2023.03.31 13:45:05 LOG3[1]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:45:05 LOG3[1]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:45:05 LOG3[1]: No more addresses to connect
2023.03.31 13:45:05 LOG5[1]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:45:05 LOG5[2]: Service [https] accepted connection from ::ffff:127.0.0.1:49909
2023.03.31 13:45:05 LOG3[2]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:45:05 LOG3[2]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:45:05 LOG3[2]: No more addresses to connect
2023.03.31 13:45:05 LOG5[2]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:45:05 LOG5[3]: Service [https] accepted connection from ::ffff:127.0.0.1:49912
2023.03.31 13:45:05 LOG3[3]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:45:05 LOG3[3]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:45:05 LOG3[3]: No more addresses to connect
2023.03.31 13:45:05 LOG5[3]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:45:06 LOG5[4]: Service [https] accepted connection from ::ffff:127.0.0.1:49915
2023.03.31 13:45:06 LOG3[4]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:45:06 LOG3[4]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:45:06 LOG3[4]: No more addresses to connect
2023.03.31 13:45:06 LOG5[4]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:45:06 LOG5[5]: Service [https] accepted connection from ::ffff:127.0.0.1:49918
2023.03.31 13:45:06 LOG3[5]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:45:06 LOG3[5]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:45:06 LOG3[5]: No more addresses to connect
2023.03.31 13:45:06 LOG5[5]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:45:06 LOG5[6]: Service [https] accepted connection from ::ffff:127.0.0.1:49921
2023.03.31 13:45:06 LOG3[6]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:45:06 LOG3[6]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:45:06 LOG3[6]: No more addresses to connect
2023.03.31 13:45:06 LOG5[6]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:45:06 LOG5[7]: Service [https] accepted connection from ::ffff:127.0.0.1:49924
2023.03.31 13:45:06 LOG3[7]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:45:06 LOG3[7]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:45:06 LOG3[7]: No more addresses to connect
2023.03.31 13:45:06 LOG5[7]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:45:06 LOG5[8]: Service [https] accepted connection from ::ffff:127.0.0.1:49928
2023.03.31 13:45:06 LOG3[8]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:45:06 LOG3[8]: s_connect: connect 127.0.0.1:8001: Connection refused (61)
2023.03.31 13:45:06 LOG3[8]: No more addresses to connect
2023.03.31 13:45:06 LOG5[8]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2023.03.31 13:45:07 LOG5[9]: Service [https] accepted connection from ::ffff:127.0.0.1:49931
2023.03.31 13:45:07 LOG3[9]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:45:07 LOG5[9]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:45:07 LOG5[9]: Service [https] connected remote server from 127.0.0.1:49933
2023.03.31 13:45:07 LOG5[10]: Service [https] accepted connection from ::ffff:127.0.0.1:49934
2023.03.31 13:45:07 LOG3[10]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:45:07 LOG5[10]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:45:07 LOG5[10]: Service [https] connected remote server from 127.0.0.1:49936
2023.03.31 13:45:07 LOG5[11]: Service [https] accepted connection from ::ffff:127.0.0.1:49937
2023.03.31 13:45:07 LOG3[11]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:45:07 LOG5[11]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:45:07 LOG5[11]: Service [https] connected remote server from 127.0.0.1:49939
2023.03.31 13:45:11 LOG5[11]: Connection closed: 367 byte(s) sent to TLS, 788 byte(s) sent to socket
2023.03.31 13:45:11 LOG5[12]: Service [https] accepted connection from ::ffff:127.0.0.1:49947
2023.03.31 13:45:11 LOG3[12]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:45:11 LOG5[12]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:45:11 LOG5[12]: Service [https] connected remote server from 127.0.0.1:49949
2023.03.31 13:45:54 LOG5[12]: Connection closed: 395 byte(s) sent to TLS, 786 byte(s) sent to socket
2023.03.31 13:45:54 LOG5[13]: Service [https] accepted connection from ::ffff:127.0.0.1:49964
2023.03.31 13:45:54 LOG3[13]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:45:54 LOG5[13]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:45:54 LOG5[13]: Service [https] connected remote server from 127.0.0.1:49966
2023.03.31 13:46:02 LOG5[13]: Connection closed: 420 byte(s) sent to TLS, 750 byte(s) sent to socket
2023.03.31 13:46:02 LOG5[14]: Service [https] accepted connection from ::ffff:127.0.0.1:49971
2023.03.31 13:46:02 LOG3[14]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:46:02 LOG5[14]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:46:02 LOG5[14]: Service [https] connected remote server from 127.0.0.1:49973
2023.03.31 13:46:37 LOG5[10]: Connection closed: 21710 byte(s) sent to TLS, 6967 byte(s) sent to socket
2023.03.31 13:46:38 LOG5[9]: Connection closed: 6245 byte(s) sent to TLS, 2645 byte(s) sent to socket
2023.03.31 13:46:47 LOG5[15]: Service [https] accepted connection from ::ffff:127.0.0.1:49988
2023.03.31 13:46:47 LOG3[15]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:46:47 LOG5[15]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:46:47 LOG5[15]: Service [https] connected remote server from 127.0.0.1:49990
2023.03.31 13:46:47 LOG5[14]: Connection closed: 250 byte(s) sent to TLS, 786 byte(s) sent to socket
2023.03.31 13:46:47 LOG5[16]: Service [https] accepted connection from ::ffff:127.0.0.1:49991
2023.03.31 13:46:47 LOG3[16]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:46:47 LOG5[16]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:46:47 LOG5[16]: Service [https] connected remote server from 127.0.0.1:49993
2023.03.31 13:46:48 LOG5[17]: Service [https] accepted connection from ::ffff:127.0.0.1:49995
2023.03.31 13:46:48 LOG3[17]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:46:48 LOG5[17]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:46:48 LOG5[17]: Service [https] connected remote server from 127.0.0.1:49997
2023.03.31 13:46:48 LOG5[16]: Connection closed: 420 byte(s) sent to TLS, 750 byte(s) sent to socket
2023.03.31 13:46:48 LOG5[18]: Service [https] accepted connection from ::ffff:127.0.0.1:50001
2023.03.31 13:46:48 LOG3[18]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:46:48 LOG5[18]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:46:48 LOG5[18]: Service [https] connected remote server from 127.0.0.1:50003
2023.03.31 13:46:51 LOG5[18]: Connection closed: 222 byte(s) sent to TLS, 750 byte(s) sent to socket
2023.03.31 13:46:51 LOG5[19]: Service [https] accepted connection from ::ffff:127.0.0.1:50005
2023.03.31 13:46:51 LOG3[19]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:46:51 LOG5[19]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:46:51 LOG5[19]: Service [https] connected remote server from 127.0.0.1:50007
2023.03.31 13:46:52 LOG5[19]: Connection closed: 275 byte(s) sent to TLS, 750 byte(s) sent to socket
2023.03.31 13:46:52 LOG5[20]: Service [https] accepted connection from ::ffff:127.0.0.1:50011
2023.03.31 13:46:52 LOG3[20]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:46:52 LOG5[20]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:46:52 LOG5[20]: Service [https] connected remote server from 127.0.0.1:50013
2023.03.31 13:46:53 LOG5[20]: Connection closed: 420 byte(s) sent to TLS, 750 byte(s) sent to socket
2023.03.31 13:46:53 LOG5[21]: Service [https] accepted connection from ::ffff:127.0.0.1:50018
2023.03.31 13:46:53 LOG3[21]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:46:53 LOG5[21]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:46:53 LOG5[21]: Service [https] connected remote server from 127.0.0.1:50020
2023.03.31 13:47:00 LOG5[21]: Connection closed: 222 byte(s) sent to TLS, 750 byte(s) sent to socket
2023.03.31 13:47:00 LOG5[22]: Service [https] accepted connection from ::ffff:127.0.0.1:50022
2023.03.31 13:47:00 LOG3[22]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:47:00 LOG5[22]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:47:00 LOG5[22]: Service [https] connected remote server from 127.0.0.1:50024
2023.03.31 13:47:01 LOG5[22]: Connection closed: 275 byte(s) sent to TLS, 750 byte(s) sent to socket
2023.03.31 13:47:01 LOG5[23]: Service [https] accepted connection from ::ffff:127.0.0.1:50028
2023.03.31 13:47:01 LOG3[23]: s_connect: connect ::1:8001: Connection refused (61)
2023.03.31 13:47:01 LOG5[23]: s_connect: connected 127.0.0.1:8001
2023.03.31 13:47:01 LOG5[23]: Service [https] connected remote server from 127.0.0.1:50030
2023.03.31 13:47:49 LOG5[15]: Connection closed: 37680 byte(s) sent to TLS, 11435 byte(s) sent to socket
2023.03.31 13:47:49 LOG5[17]: Connection closed: 7494 byte(s) sent to TLS, 3174 byte(s) sent to socket
